# Generated by Django 4.0.5 on 2022-06-26 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='name',
            new_name='nome',
        ),
    ]
